#!/bin/sh
#
# Quick test to ensure it at least compiles on all supported platforms.

set -euC

go test -race .

GOOS=darwin  go build
GOOS=freebsd go build
#GOOS=illumos go build
GOOS=linux   go build
#GOOS=solaris go build
GOOS=windows go build
